### ISSUE TITLE
Bytecode: 32-bit write is actually four 8-bit writes

### ISSUE THREAD

**Issue by Reperator** [mirage/ocaml-cstruct#229] opened 2019-02-28 21:41 UTC
First of all: I'm not sure if you'd consider this an actual issue; feel free to close it if it's not appropriate. 

I'm writing [ixy.ml](https://github.com/ixy-languages/ixy.ml), an OCaml driver for Intel 82599 NICs. The NIC is programmed by writing to a magic `mmap`ed file. I'm wrapping this file in a `Cstruct.t` (I had to change `Unix_cstruct.of_fd` to map the file as `MAP_SHARED`) and writing to it using `Cstruct.LE.set_uint32`. As far as I can tell this uses the `%caml_bigstring_set32` primitive which when compiled as bytecode calls [`caml_ba_uint8_set32`](https://github.com/ocaml/ocaml/blob/17b64ac2b25f8bc70eca5c589fcb9849f880bdde/runtime/bigarray.c#L796). This function writes the 4 bytes separately which would usually be fine (if a bit slow), but unfortunately the 82599 NIC wants its writes done 32 bit at a time. [The datasheet](https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/82599-10-gbe-controller-datasheet.pdf) states:
>All registers should be accessed as a 32-bit width on reads with an appropriate software mask, if needed. A software read/modify/write mechanism should be invoked for partial writes.

This means my driver doesn't work when using the bytecode compiler and cstruct's functions to access `Cstruct.t` (as far as I can tell). I'm currently working around this issue by using the `mmap`ed bigarray directly and calling [my own {get,set}_32](https://github.com/ixy-languages/ixy.ml/blob/9880eea0f5edbb54384e3e80acfc4f748aa4cb2e/lib/memory.c#L35).

So is this a cstruct issue? I think this could be worked around by specifying an additional external function specific to bytecode in the `external` declaration. This might be very slow though, since the bytecode function would get all its arguments in an array. I'd be happy to implement these primitives for the bytecode backend and create a PR if there's interest.

Another tangential question: Should there be additional getter/setter functions that include memory barriers? That'd be nice for writing drivers where reordering of memory accesses could become problematic.

**Comment by dinosaure** [comment] 2019-02-28 23:08
First, thank for your work, I saw your conference at the last CCC and we are really happy to see OCaml, and, more precisely `ocaml-cstruct` used to this kind of software.

Then, I need to explain some points from what you said:

* It seems than Intel 82599 NIC has a _Common flat address space for load/store access_. That mostly say that we should use your driver on a 32-bits CPU. However, in the OCaml world, `int` is encoded in 31 bits in a 32-bits CPU target and 63 bits in a 64-bits architecture. To have a completely 32-bits integer, we use the [Int32](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Int32.html) module which is a _boxed_ value.

[About your code](https://github.com/ixy-languages/ixy.ml/blob/9880eea0f5edbb54384e3e80acfc4f748aa4cb2e/lib/memory.c#L39), in a 32-bits CPU, [`Val_long`](https://github.com/ocaml/ocaml/blob/d3e73595e55e84250fa77f04e9c239dee1224b7b/runtime/caml/mlvalues.h#L73) will delete 1 bit of your value - and I think, it's not what you want. About this behavior, you can precisely look what happen in [config.h](https://github.com/ocaml/ocaml/blob/trunk/runtime/caml/config.h) or read [this article](https://blog.janestreet.com/what-is-gained-and-lost-with-63-bit-integers/) about the GC bit. So it can be a problem.

* Unfortunately, if you really want to compile your code to a _bytecode_, the only way to really read/write a 32-bits integer is to write this primitive/operation in C - like what you did (but use `caml_copy_int32`/`Int32_val` instead `Val_long`/`Long_val` if you want to continue the 32-bits CPU support).

* If you want a native support, it's possible (but, again, it's depend on your target __and__ your code) to read an 32-bits integer in one time. `caml_bigstring_setint32{,u}` generates a `Pbigstring_set` primitive, which is _translated_ to a [`unaligned_set`](https://github.com/ocaml/ocaml/blob/74182ae67992cb12b47b0b20a41ad3bd917920e4/asmcomp/cmmgen.ml#L2653). Then, `unaligned_set` __can__ be compiled to a [`Cstore`](https://github.com/ocaml/ocaml/blob/74182ae67992cb12b47b0b20a41ad3bd917920e4/asmcomp/cmmgen.ml#L1230) (so, this case can not be done for `arm64`, `arm` and `s390x` targets). At the final step, you should have the `mov` instruction. Of course, it's only if we have a planets alignment apparently.

* Finally, about `external` __and__ _bytecode_ compilation, in `*.mli` file, you should define your function with `external` too (instead `val`) to let the compiler to call directly the C function instead to wrap it inside a fake caml function.

Finally, I think, the problem still exists but in a gray area between `ocaml-cstruct` and the compiler. Be able to read/write at a time in any target/context can be done by a C code indeed - and I think, this is the best solution. If we can integrate it in `ocaml-cstruct`, I'm not sure. Mostly because we don't want to have too many C stubs - however, for this kind of problems (I mean, write a driver in OCaml), it can be relevant - cc @mirage/core.

NOTE: Never use [`Obj.magic`](https://github.com/ixy-languages/ixy.ml/blob/master/lib/util.ml#L1)

**Comment by Reperator** [comment] 2019-02-28 23:53
Glad to hear it!

I know about all the value representations; I've read RWO a while back. We're not targeting 32-bit CPUs; the driver [detects 32-bit systems and quits immediately](https://github.com/ixy-languages/ixy.ml/blob/master/lib/ixy.ml#L176). I'm trying to mostly get rid of `int32` in the hot path for performance reasons which is what prompted me to write those C functions in the first place. Only later did I realize that this coincidentally also fixed the bytecode problems.

I don't really care about bytecode; it's just something I noticed while comparing bytecode and native code performance for a presentation (spoiler alert: native code is ~30x faster). We're currently also not targeting anything besides x86_64 Linux (for now; I'll be at the mirage retreat next week and I'll be looking into making the driver somewhat mirage-compatible).

Which  `external` declaration should I expose? I'm not seeing any that should be public but aren't. Or were you not talking about my code?

Regarding the use of `Obj.magic`: What's the most idiomatic way to split an `int64` into two `int32`? 
`(Int32.of_int @@ Int64.to_int @@ Int64.shift_right i64 32), (Int32.of_int @@ Int64.to_int @@ Int64.logand i64 0xffffffffL)`? Kind of ugly, but `Obj.magic` isn't pretty either. Also doesn't work on 32-bit machines, but so does the rest of the driver.

**Comment by dinosaure** [comment] 2019-03-01 10:14
About Mirage compatible, I think the biggest problem while be the `mmap` function which depends on `unix`. But @diml wrote a package [`mmap`](https://github.com/mirage/mmap) about that. The translation should be easy.

About `external`, it's common to put it in `*.mli` (like what [`bigstringaf`](https://github.com/inhabitedtype/bigstringaf/blob/master/lib/bigstringaf.mli#L52) does - but it's not very important.

To avoid your `Obj.magic` your code (eg. ``) is good. But instead to pass by an `int`, you can use directly `Int64.to_int32` and you should not use the `@@` operator (which can add [a regression](https://discuss.ocaml.org/t/benchmarking-bucklescript-vs-js-of-ocaml/3191/15) about performances).

Then, the compiler can be smart enough to _unbox_ `int32` and `int64` in some ways. But the best to exactly know what happen is to read the CMM output (with `-dcmm` option) which is close to what OCaml will emit at the end.

Finally, if you really aware about performance, you should try to switch to `ocaml+flambda` which adds a much more smarter optimization pass - inline, unbox and specialization will be done magically. And then, I will go to the Marrakesh retreat with @chambart (one of the authors of `flambda` will going too) and I will be happy to help you to optimize your code.

**Comment by Reperator** [comment] 2019-03-01 10:42
This may be a dumb question, but which file would we `mmap` anyways? The driver needs the magic register file provided by Linux as well as packet buffers that don't move around in physical memory (which is what hugepages on Linux happen to provide); does Mirage support these? I assumed the bigger problem would be to get PCIe communication in the first place (bus enumeration, etc.).

Wow, no idea how I missed `Int64.to_int32`; I feel dumb now.

I didn't know about the `@@` operator's performance, thanks for pointing that out. Does the same go for `|>`? I'm using that in a few places.

I'm already using flambda; it's ~30% faster. I still had to [add `[@@inline]` attributes](https://github.com/ixy-languages/ixy.ml/commit/f6aaf78ce7c8ef5a906685e7da20c3adb263324d) unfortunately. If you're curios, these are the measurements I made yesterday:
![ml-batch-33](https://user-images.githubusercontent.com/10628294/53632308-e1fd5800-3c14-11e9-9ca3-3852201b8622.png)

`master` doesn't have the `[@@inline]` attributes and lacks the C functions for register accesses (i.e. uses `Cstruct.LE.{g,s}et_uint32`). `list` uses `list`s instead of `array`s for storing packet buffers.

See you at the retreat then!

**Comment by dinosaure** [comment] 2019-03-01 11:11
> This may be a dumb question, but which file would we `mmap` anyways? The driver needs the magic register file provided by Linux as well as packet buffers that don't move around in physical memory (which is what hugepages on Linux happen to provide); does Mirage support these? I assumed the bigger problem would be to get PCIe communication in the first place (bus enumeration, etc.).

I'm not an expert about this question but may be @hannesm or @yomimono can have a response about that. What I said is about `Unix` module [here](https://github.com/ixy-languages/ixy.ml/blob/44d4ccbeb5661c605db7eab6eaf65cea6387bfc1/lib/util.ml#L8) which can not be compiled for a mirage target - we want to avoid any call to the `Unix` module.

We have several ways to _abstract_ this kind of code. One of them is about functor and abstract these _syscalls_ with a signature (and then, choose the implementation depending on the target) - however, functor has a cost about performance.

> I didn't know about the `@@` operator's performance, thanks for pointing that out. Does the same go for `|>`? I'm using that in a few places.

Probably, yes.

> I'm already using flambda; it's ~30% faster. I still had to [add `[@@inline]` attributes](https://github.com/ixy-languages/ixy.ml/commit/f6aaf78ce7c8ef5a906685e7da20c3adb263324d) unfortunately.

From what I know about `flambda` ~30% faster is common - but we probably can have something better - but I need to spend my time on your code for that :-) . Then, with or without `flambda`, you can keep `[@@inline]` attribute in your master branch - the compiler will just discard them.

See you at the retreat! I will try to optimize that 👍 !

**Comment by avsm** [comment] 2019-03-01 11:16
You don't need mmap -- the particular hardware library can just return Cstruct.t values representing the area of memory that you want to write to; see e.g. https://github.com/mirage/mirage-xen/blob/master/lib/start_info.ml for the Xen start_info structures that are similar.

**Comment by Reperator** [comment] 2019-03-01 11:32
The start_info binding is not bidirectional, though. [I'm doing the same for `uname()`.](https://github.com/ixy-languages/ixy.ml/blob/master/lib/uname.ml)

We need to both read from and write to this memory area. Anything I should read up on regarding hardware communication before the retreat? Should we focus on Xen, Solo5 or mirage-unix?

Also we're getting kind of off-topic; any opinions on my initial question?

**Comment by avsm** [comment] 2019-03-02 00:09
To answer your question, cstruct should expose atomic 32-bit and 64-bit writes where supported by the architecture.  It's worth asking @chambart about how best to do this via ocplib-endian at the retreat, perhaps...

**Comment by mato** [comment] 2019-03-02 11:04
On Friday, 01.03.2019 at 03:32, Fabian Bonk wrote:
> The start_info binding is not bidirectional, though. [I'm doing the same for `uname()`.](https://github.com/ixy-languages/ixy.ml/blob/master/lib/uname.ml)
> 
> We need to both read from and write to this memory area. Anything I should read up on regarding hardware communication before the retreat? Should we focus on Xen, Solo5 or mirage-unix?

FYI, Solo5 does not currently have any abstractions for interfacing to
shared memory on the host. If I understand correctly, this is the minimum
you need to run an ixy-style driver without interrupts. If you want to get
something working quickly I'd try with mirage-unix first.

**Comment by hannesm** [comment] 2019-04-09 17:08
not clear what to do with this issue. The main issues "32 bit write is 4 times 8 bit writes" is tracked/enhanced in https://github.com/ocaml/ocaml/pull/2304 and we can't do much in Cstruct about it. The various comments here include lots of other information, which I'm not sure are related to issues or not. I'll close this now, please feel free to reopen or comment here if I missed something.

**Closed by hannesm** 2019-04-09 17:08 UTC

**Comment by djs55** [comment] 2019-04-12 06:45
For reference was a similar issue in Mirage here: https://github.com/mirage/shared-memory-ring/pull/5
